name: drupaltest
recipe: drupal8
services:
  my-service:
    type: redis
  cache:
    type: redis:4.0
    portforward: 6380
    persist: true
config:
  webroot: web
tooling:
  drupal:
    cmd:
      - "vendor/bin/drupal"
  redis-cli:
    service: cache
