name: drupaltest
recipe: drupal8
services:
  redis:
      type: redis
      portforward: true
config:
  webroot: web
tooling:
  drupal:
    cmd:
      - "vendor/bin/drupal"
  redis-cli:
    service: redis